github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-example-chart
    - name: activiti-cloud-example-chart-security-policies
    - name: activiti-cloud-example-chart-modeling
